"""
Clean Manual Test Data Script for Samagra UPI Automation
=========================================================
This script automatically cleans up and deletes all test courses, batches,
payment sessions, payment submissions, statement imports, and reconciliation runs
generated by `seed_manual_test_data.py`.

Usage:
  Direct Python: python clean_manual_test_data.py
  Docker Compose: docker compose exec backend python /app/clean_manual_test_data.py
"""

import asyncio
import os
import sys

# Add backend directory to sys.path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.join(BASE_DIR, "backend")
if os.path.exists(BACKEND_DIR) and BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

# Database connection fallback for running outside container
if "DATABASE_URL" not in os.environ:
    os.environ["DATABASE_URL"] = "postgresql+asyncpg://app_user:change_me_to_a_secure_password@127.0.0.1:5432/training_payments"

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy import select, delete
from app.models.course import Course
from app.models.batch import Batch
from app.models.payment_session import PaymentSession
from app.models.payment_submission import PaymentSubmission
from app.models.statement_import import StatementImport
from app.models.bank_transaction import BankTransaction
from app.models.reconciliation_run import ReconciliationRun
from app.models.reconciliation_result import ReconciliationResult

SEED_COURSES = [
    "Full Stack Web Development",
    "Data Science & Artificial Intelligence",
    "Cloud Computing & DevOps",
]

async def main():
    db_url = os.environ["DATABASE_URL"]
    if "postgres:5432" in db_url and not os.path.exists("/.dockerenv"):
        db_url = db_url.replace("postgres:5432", "127.0.0.1:5432")

    engine = create_async_engine(db_url, echo=False)
    async_session = async_sessionmaker(engine, expire_on_commit=False)

    print("=" * 70)
    print("🧹 CLEANING MANUAL TEST DATA FROM SAMAGRA UPI AUTOMATION")
    print("=" * 70)

    async with async_session() as db:
        # Find test courses
        stmt = select(Course).where(Course.name.in_(SEED_COURSES))
        res = await db.execute(stmt)
        courses = list(res.scalars().all())

        if not courses:
            print("\nNo seeded test courses found in database.")
        else:
            course_ids = [c.id for c in courses]
            
            # Find test batches
            stmt_b = select(Batch).where(Batch.course_id.in_(course_ids))
            res_b = await db.execute(stmt_b)
            batches = list(res_b.scalars().all())
            batch_ids = [b.id for b in batches]

            # Find test payment sessions
            stmt_ps = select(PaymentSession).where(PaymentSession.course_id.in_(course_ids))
            res_ps = await db.execute(stmt_ps)
            payment_sessions = list(res_ps.scalars().all())
            ps_ids = [ps.id for ps in payment_sessions]

            # 1. Delete reconciliation results for these sessions or runs
            if ps_ids:
                await db.execute(delete(ReconciliationResult).where(ReconciliationResult.payment_session_id.in_(ps_ids)))
            if batch_ids:
                await db.execute(delete(ReconciliationRun).where(ReconciliationRun.batch_id.in_(batch_ids)))

            # 2. Delete payment submissions
            if ps_ids:
                await db.execute(delete(PaymentSubmission).where(PaymentSubmission.payment_session_id.in_(ps_ids)))

            # 3. Delete payment sessions
            if ps_ids:
                await db.execute(delete(PaymentSession).where(PaymentSession.id.in_(ps_ids)))

            # 4. Delete batches
            if batch_ids:
                await db.execute(delete(Batch).where(Batch.id.in_(batch_ids)))

            # 5. Delete courses
            await db.execute(delete(Course).where(Course.id.in_(course_ids)))

            # 6. Delete test statement imports if named demo_test_statement.csv
            stmt_si = select(StatementImport).where(StatementImport.filename.in_(["demo_test_statement.csv", "demo_reconciliation_statement.csv"]))
            res_si = await db.execute(stmt_si)
            imports = list(res_si.scalars().all())
            si_ids = [si.id for si in imports]
            if si_ids:
                await db.execute(delete(BankTransaction).where(BankTransaction.statement_import_id.in_(si_ids)))
                await db.execute(delete(StatementImport).where(StatementImport.id.in_(si_ids)))

            await db.commit()

            print(f"\nDeleted {len(courses)} Courses: {[c.name for c in courses]}")
            print(f"Deleted {len(batches)} Batches: {[b.name for b in batches]}")
            print(f"Deleted {len(payment_sessions)} Payment Sessions & Submissions")
            print("Successfully purged seeded test data from PostgreSQL!")

    # Remove generated CSV from root directory
    csv_paths = [os.path.join(BASE_DIR, "demo_test_statement.csv"), "/tmp/demo_test_statement.csv"]
    for path in csv_paths:
        if os.path.exists(path):
            try:
                os.remove(path)
                print(f"Removed local test statement file: {path}")
            except Exception:
                pass

    print("\n" + "=" * 70)
    print("✨ CLEANUP COMPLETE!")
    print("=" * 70)

if __name__ == "__main__":
    asyncio.run(main())
